spring:
  data:
    redis:
#      host: 192.168.101.17
      host: localhost
      port: 6379
#      password: puxinxiaolin
      password: root
#      database: 0
      database: 2
      timeout: 5s
      lettuce:
        pool:
          max-active: 200  # 连接池最大连接数
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10  # 连接池最大空闲连接
          min-idle: 0  # 连接池最小空闲连接

logging:
  level:
    com.puxinxiaolin.xiaolinshu.auth.domain.mapper: debug